var mongoose = require('mongoose');
var Schema = mongoose.Schema;

module.exports = new Schema({
    "followed": Boolean,
    "house": String,
    "sex": Number,
    "tagComparator": Object,
    "isCheckSchool": Boolean,
    "education": String,
    "id": String,
    "city": Number,
    "isCheckSalary": Boolean,
    "marriageStatus": String,
    "isUserBlock": Boolean,
    "isVip": Boolean,
    "isCheckCorpVerify": Boolean,
    "province": Number,
    "isOnline": Number,
    "isSayHi": Boolean,
    "isSuperVip": Boolean,
    "company": String,
    "avatarType": String,
    "isNormalVip": Boolean,
    "height": String,
    "salary": String,
    "school": String,
    "photoCount": Number,
    "isCheckId": Boolean,
    "albumId": Number,
    "url": String,
    "nickName": String,
    "age": Number,
    "isCheckCorp": Boolean,
    "isCheckMobile": Boolean,
    "avatar": String,
    "car": String,
    "following": Boolean,
    "position": String,
    "industry": String
});